Rails.application.routes.draw do
  root to: 'pages#home'

  get 'cards',                  to: 'pages#index'
  get 'cards/navigation',       to: 'pages#navigation'
  get 'cards/all-cards',        to: 'pages#all_cards'
  get 'cards/sans-rejects',     to: 'pages#sans_rejects'
  get 'cards/sans-borderline',  to: 'pages#sans_borderline'
  get 'cards/final',            to: 'pages#final'

  get 'home',                   to: 'pages#home'
  get 'about',                  to: 'pages#about'
  get 'the-program',            to: 'pages#the_program'
  get 'is-this-for-me',         to: 'pages#is_this_for_me'
  get 'course-dates',           to: 'pages#course_dates'
  get 'tuition',                to: 'pages#tuition'
  get 'info-sessions',          to: 'pages#info_sessions'
  get 'front-end-bootcamp',     to: 'pages#front_end_bootcamp'
  get 'part-time-courses',      to: 'pages#part_time_courses'
  get 'launch-program',         to: 'pages#launch_program'
  get 'employers',              to: 'pages#employers'
  get 'blog',                   to: 'pages#blog'
  get 'apply',                  to: 'pages#apply'
  get 'contact',                to: 'pages#contact'
end
